//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public int department_id { get; set; }
        public string salary { get; set; }
        public int Job_id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual Tbl_Job Tbl_Job { get; set; }
    }
}
